---
title: "Vitamin D and Covid-19"
description: "A comprehensive list of research related to vitamin D and Covid-19"
output:
  rmarkdown::html_document:
    theme: lumen
    anchor_sections: true
---
To make suggestions and changes see the Github repo: [Vitamin_d_covid](https://github.com/GShotwell/vitamin_d_covid/blob/master/index.Rmd)

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(metathis)
meta() %>%
  meta_description(
    "A comprehensive list of research related to vitamin D and Covid-19"
  ) %>% 
  meta_name("github-repo" = "GShotwell/vitamin_d_covid") %>% 
  meta_viewport() %>% 
  meta_social(
    title = "Vitamin D and Covid",
    url = "https://vitamin-d-covid.shotwell.ca/",
    image = "https://cdn.pixabay.com/photo/2014/04/05/11/40/pill-316601_960_720.jpg",
    image_alt = "Several gold vitamin D pills",
    og_type = "website",
    og_author = c("Gordon Shotwell"),
    twitter_card_type = "summary",
    twitter_creator = "@gshotwell"
  )
```

# The argument for supplementation
- Vitamin D reduces the risk of [other](https://www.bmj.com/content/356/bmj.i6583) acute respiratory infections. One interesting finding of this meta-analysis is that people who were very deficient (less than 25 nmol/L) saw the largest protective effect with an adjusted odd ratio of 0.58 and a 95% CI of 0.40 to 0.82. These are the same populations which seem to be at risk for severe Covid-19
- Calcitriol, the active form of Vitamin D [is active](https://www.biorxiv.org/content/10.1101/2020.06.21.162396v1) against the SARS-COV2 virus
- Patients treated with calcifediol are [less likely](https://www.sciencedirect.com/science/article/pii/S0960076020302764?via%3Dihub#tbl0005) to be admitted to the ICU than controls
- Several studies have now observed lower vitamin D levels among severe Covid-19 patients
- [Vitamin D is very low risk](https://www.preprints.org/manuscript/202005.0265/v1) an adverse events of vitamin D supplementation can be easily managed by clinicians

# Direct research on vitamin D and Covid

### Supplementation studies

**Randomized**

*Supports link to vitamin D*

- A [parallel pilot randomized open label](https://www.sciencedirect.com/science/article/pii/S0960076020302764?via%3Dihub#tbl0005) trial of 76 patients in Spain found that the administration of calcifediol reduced ICU admission and mortality. Of the 50 patients treated with calcifediol only one required ICU care, compared with 13/26 patients in the control group. A [subsequent statistical analysis](https://www.medrxiv.org/content/10.1101/2020.11.08.20222638v1) showed that decreased ICU admissions were not due to uneven distribution of comorbidities or other prognostic indicators, to imperfect blinding, or to chance, but were instead associated with the calcifediol intervention.  (Castillo et all, August 2020)
- A randomized, [placebo controlled trial](https://pmj.bmj.com/content/early/2020/11/12/postgradmedj-2020-139065.full) found that therapeutic, high-dose cholecalciferol supplementation led to SARS-CoV-2 RNA negative status in additional 41.7% of mildly symptomatic Covid patients (p<0.001) and was useful for viral SARS-CoV-2 RNA clearance.

*Does not support vitamin D link*

- A randomized, placebo controlled [trial](https://www.medrxiv.org/content/10.1101/2020.11.16.20232397v1) of 240 patients found that a one-time supplementation of 200,000 IU of vitamin D, on average 10 days after symptom onset did not reduce the length of hospital stay in severe Covid-19 patients. The treatment was safe and well tolerated. 

**Non-Randomized**

- A [small cohort trial](https://www.sciencedirect.com/science/article/pii/S0899900720303002)  found that just 16% of patients who received vitamin D, magnesium, and vitamin B12 required oxygen compared with 61.5% of the previous cohort who did  not receive DBM supplementation. (Chuen Wen Tan, October 2020)
- A [retrospective study](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3690902) found that hospitalized patients who were treated with vitamin D were less likely to die than those who did not receive vitamin D. (Ling et all, October 2020)
- [A retrospective study](https://www.sciencedirect.com/science/article/pii/S096007602030296X#fig0010) found that French nursing home residents who had recently received a bolus dose of vitamin D were more likely to survive a Covid-19 infection than residents who had not recently received a supplement. 92%  of the 57 people who received vitamin D survived, while 66% of the 9 people in the cooperator group survived. (Anweller et. al, October 2020)
- [A retrospective study](https://www.mdpi.com/2072-6643/12/11/3377) found that regular bolus vitamin D supplementation was associated with less severe COVID-19 and better survival in frail elderly. (Anweller et. al, November 2020)

### Covid severity associated with serum vitamin D levels

#### Meta analyses

- A [metaanalysis](https://www.tandfonline.com/doi/abs/10.1080/10408398.2020.1841090?journalCode=bfsn20) of studies on Vitamin D and Covid-19 found that, overall, vitamin D was a risk factor for Covid-19, especially severe disease. (Pereira et al, November 2020)

#### Pre-infection blood samples

*Supports link to vitamin D*

1) A [retrospective cohort](https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2770157) study found that Chicago patients who were likely vitamin D deficient were more likely to test positive for Covid-19. (Meltzer et al, May 2020)
1) An [Israeli study](https://febs.onlinelibrary.wiley.com/doi/abs/10.1111/febs.15495) of 7,000 patients with pre-Covid serum vitamin D tests found that vitamin D levels were associated with Covid infection and hospitalization. (Eugene Merzon et al, July 2020)
1) An [analysis](https://www.medrxiv.org/content/10.1101/2020.09.04.20188268v1) of Israeli vitamin D tests performed between 2010 and 2019 found that vitamin D deficiency predicted Covid-19 infection. (Israel et al, August 2020)
1) [An analysis](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0239252#pone-0239252-g002) of 190,000 patients found that the probability of testing positive was associated with vitamin D levels. This association held across all age groups, ethnicities and geographies.  (Kaufman et all, Sept 2020)

*Does not support vitamin D link*

- Vitamin D levels between 2006-2010 [were associated](https://www.sciencedirect.com/science/article/pii/S1871402120301156) with Covid-19 mortality, but not after controlling for other variables in the data set. It's hard to make inferences from 10 year old blood samples because there's a causal story in which low vitamin D in 2010 _increases_ vitamin D in 2020 because that group is likely to supplement. (Hastie et al, July 2020)


#### Post-infection blood samples

*Supports vitamin D link*

1) A re-analysis of [107 Swiss blood samples](https://www.mdpi.com/2072-6643/12/5/1359/htm) found that PCR positive patients had 25-hydroxyvitamin D concentrations half that of PCR negatives. This finding held after stratifying for age and gender. (Avolio et 1) l, April 2020)
1) Hospitalized male Covid-19 patients [were found](https://www.medrxiv.org/content/10.1101/2020.05.01.20079376v1) to have lower vitamin D levels than controls. (De Smet et al, May 2019)
1) A observational [study from Belgium](https://academic.oup.com/ajcp/advance-article/doi/10.1093/ajcp/aqaa252/6000689?searchresult=1) found that vitamin D deficiency is correlated with the risk for hospitalization for COVID-19 pneumonia and predisposes to more advanced radiological disease stages. (De Smet, November 2020)
1) Vitamin D deficiency [was more common](https://onlinelibrary.wiley.com/doi/full/10.1111/cen.14276) among ITU Covid patients than the general population in a Newcastle hospital.  (Panagiotou et all, June 2020)
1) A [Mexican study](https://www.medigraphic.com/pdfs/sanmil/sm-2020/sm201_2za.pdf) found that patients with vitamin D serum levels bellow 8 ng/mL had 3.68 higher risk of dying from COVID-19. (Arturo Rodríguez Tort et al, April 2020)
1) A [Iranian study](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0239799) (Maghbooli et al, September 2020) found there was a significant association between vitamin D sufficiency and reduction in clinical severity. Note that an [expression of concern](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0240965) was filed for this publication.
1) A [study](https://link.springer.com/article/10.1007/s40618-020-01370-x) of 42 COVID-19 patients in a respiratory ICU found that 50% of vitamin D deficient patients died after 10 days compared with 5% of non-deficient patients. (Carpagnano et all, August 2020)
1) A [prospective cohort study](https://www.mdlinx.com/journal-summary/vitamin-d-status-and-outcomes-for-hospitalised-older-patients-with-covid-19/i68lJrN18PCbGXMwzC0tU) found that vitamin D deficiency was more common among Covid positive patients presenting with Covid symptoms than Covid negative patients, and suggested that it could be considered as a diagnostic tool. (Baktash V et all, August 2020)
1) [A study](https://www.sciencedirect.com/science/article/pii/S0168170220310558) of patients presenting with Covid symptoms at an Iranian hospital found that vitamin D deficiency and ACE dysregulation were more common among those who tested positive for Covid-19. (Mardenia et all, August 2020)
1) [A German Study](https://www.mdpi.com/2072-6643/12/9/2757/htm) found that vitamin D status was associated with need for mechanical ventilation and death. (Radujkovic et al, August 2020)
1) [A small prospective cohort study](https://pmj.bmj.com/content/early/2020/08/26/postgradmedj-2020-138712?s=09) of older adults found that vitamin D deficiency was associated with mechanical ventilation, but not death.  (Baktash et all, September 2020)
1) [A Turkish study](https://link.springer.com/article/10.1007/s12603-020-1479-0) found that vitamin D deficiency was associated with mortality. (Karahan & Katkat October 2020)
1) [A study](https://www.medrxiv.org/content/10.1101/2020.10.05.20206706v1) of UK health professionals found that vitamin D deficient individuals were more likely to be seropositive for Covid antibodies. (Aduragbemi et all, October 2020)
1) A study of [Covid positive children](https://onlinelibrary.wiley.com/doi/10.1002/ppul.25106) found that children with Covid had lower vitamin D levels than healthy controls. (Yilmaz & Sen, October 2020)
1) A [case control study](https://www.tandfonline.com/doi/full/10.1080/07315724.2020.1826005) in China found that vitamin D deficiency was higher in Covid patients than healthy controls, and that it was associated with disease severity. (Ye et. al, October, 2020)
1) A retrospective [case control](https://academic.oup.com/jcem/advance-article/doi/10.1210/clinem/dgaa733/5934827) study of 216 hospitalized patients found that 80% of Covid patients were vitamin D deficient, while just 42% of matched controls were deficient. The study did not find that vitamin D deficiency was associated with disease outcome. (Hernández et al, October 2020)
1) A [study](https://link.springer.com/article/10.1007%2Fs00394-020-02411-0) of 74 hospitalized patients found that vitamin D deficiency was associated with Covid lung involvement, and mortality. (Abrishami et all, October 2020)
1) A [prospective observational study](https://www.nature.com/articles/s41598-020-77093-z) found that criticlaly ill Covid patients had higher rates of vitamin D deficiency than asymptomatic patients. (Jain et al, November 2020)

*Does not support link to vitamin D*

1) A [small trial](https://pubmed.ncbi.nlm.nih.gov/32960622/) did not find an association between vitamin D deficiency and Covid-19 severity. The study did find an association among younger patients. (Macaya et. al, September 2020)
1) A [case-control study](https://www.researchsquare.com/article/rs-96491/v1) did not find that Covid positive patients had lower vitamin D levels than patients hospitalized with non-Covid pneumonia or a set of non-respiratory conditions. 
The comparator groups in this study are a bit strange because low vitamin D levels are implicated in almost all of the diagnoses included in this study. See the comments associated with the paper. (Tomasti et al, October 2020)
1) An [Italian study](https://econtent.hogrefe.com/doi/abs/10.1024/0300-9831/a000687) of 347 patients did not find that hospitalized Covid patients had lower serum vitamin D than non-Covid patients. The authors note that "Because a large portion of patients were below the suggested 30 ng/mL threshold, we can’t exclude that VitD supplementation, restoring normal levels, might be beneficial in reducing the risk of infection." (Ferrari & Locatelli, November 2020)
1) A [study](https://www.medrxiv.org/content/10.1101/2020.11.07.20227512v1) of 135 hospitalized patients in the Netherlands was not assoicated with need for mechanical ventilation or death. The author's note that vitamin K may be an important factor along with vitamin D. (Walk et al, November 2020)

### In vitro evidence
- Calcitriol, the active form of Vitamin D [is active](https://www.biorxiv.org/content/10.1101/2020.06.21.162396v1) against the SARS-COV2 virus. (Chee Keng Mok et al, June 2020)
- An in vitro [study](https://www.biorxiv.org/content/10.1101/2020.12.02.408153v1) found that the antimicrobial peptide LL-37, which is upregulated by vitamin D, binds to the SARS-COV2 spike protein. The study "supports the prophylactic use of vitamin D to induce LL-37 that protects from SARS-CoV-2 infection, and the therapeutic administration of vitamin D for the treatment of COVID-19 patients". (Roth et al, November 2020)

### Non-clinical causal data

*Supports vitamin D*

- Evidence supports a [vitamin-D causal model](https://www.medrxiv.org/content/10.1101/2020.05.01.20087965v1) more than an acausal one. (Davies et al, June 13 2020)
- A [Mendelian randomisation analysis](https://nutrition.bmj.com/content/early/2020/05/20/bmjnph-2020-000096) of excess COVID-19 mortality of African-Americans in the US suggests that vitamin D is a risk factor for Covid Mortality. (Martin Kohlmeier, May 2020)

*Does not support vitamin D*

- A [Mendelian randomization](https://www.medrxiv.org/content/10.1101/2020.08.09.20171280v1.article-info) using genes associated with vitamin D deficiency did not support a causal connection between vitamin D and Covid-19 mortality. It appears that this study used UK Biobank data, but the date of the samples were not disclosed. (Liu et al, August 2020)
- Another [Mendelian randomization](https://www.medrxiv.org/content/10.1101/2020.09.08.20190975v2.full.pdf) based on UK biobank and other genetic datasets found that people of European descent who were genetically predisposed to high vitamin D levels did not change their risk of contracting Covid, but seemed to increase their risk of hospitalization. (Butler-Laporte, September 2020)


### Ecological studies

- A study out of [Northwestern University](https://link.springer.com/article/10.1007%2Fs40520-020-01677-y) found that the vitamin D status of a country's elderly population was associated with the number of severe cases of Covid-19 in that country. (Daneshkhah1 et al, April 2020)
- There was a [strong correlation](https://www.medrxiv.org/content/10.1101/2020.06.24.20138644v1) between vitamin D levels and European mortality which increased over time.  (Chuen Wen Tan, June 2020)
- UVB radiation, which the skin uses to manufacture vitamin D is [associated](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3586555#.XrA5awDBBLE.twitter) with lower death rates and case fatality rates. (Moozhipurath et al, May 1st 2020)
- Covid-19 deaths-per-million appears to [vary by latitude](https://www.ncbi.nlm.nih.gov/pubmed/32311755). (Rhodes et al, June 2020)
- Latitude [was not associated](https://www.cmaj.ca/content/192/21/E566) with a proportional increase in cases during one week of March. (Jüni et al, June 2020)
- Latitude is a significant predictor of Covid mortality after [controlling for age](https://nutrition.bmj.com/content/3/1/118). (Rhodes et al, July 2020)
- Vitamin D levels were [inversely associated](https://link.springer.com/article/10.1007/s40520-020-01619-8) with cases per million in Europe, but not with deaths per million. (Sing, Kaur, Kumar Sigh, August 2020)
- The fall 2020 outbreaks in Europe [appear to be correlated](https://www.medrxiv.org/content/10.1101/2020.10.28.20221176v2) with latitude but not temperature. (Warland, November 2020)

# Vitamin D background and previous studies

- Vitamin D Supplementation to Prevent Acute Respiratory Tract Infections: [Systematic Review and Meta-Analysis of Individual Participant Data](https://pubmed.ncbi.nlm.nih.gov/28202713/) (Martineau et al, February 2017)
- An [2020 meta analysis](https://www.medrxiv.org/content/10.1101/2020.07.14.20152728v1) found that while vitamin D supplementation did reduce the rate of ARI, there was evidence of publican bias in the research. (Jolliffe et all, July 2020)
- Vitamin D and Influenza — [Prevention or Therapy?](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6121423/) (Gruber-Bzura, August 2018)
- Vitamin D and [the anti-viral state](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3308600/) (Beard et al, January 2011)

# Clinical guidance

*Supports supplementation*

- The Frontline Covid-19 Critical Care Alliance [recommends](https://covid19criticalcare.com/) vitamin D as a Covid-19 therapeutic for inpatient, outpatient, and prophylactic use.
- [Israel](https://www.theyeshivaworld.com/news/headlines-breaking-stories/1911344/health-ministry-urges-israelis-to-take-vitamin-d-to-fight-covid-19.html) started recommending vitamin D in October 2020.
- [Slovenia](https://www.bmj.com/content/369/bmj.m1820/rr) has begun administering vitamin D to residents of nursing homes and health care workers. 
- The French National Academy of Medicine [recommends](https://www.connexionfrance.com/French-news/French-doctors-advise-vitamin-D-to-counter-Covid-this-winter#.X6V58E6XMGU.twitter) that people over 60 be tested for vitamin D deficiency and given a bolus dose of 50,000 to 100,000 IU. It further recommends that all Covid positive patients take 800 to 1000 IU a day upon diagnosis.
- A Swiss expert panel [recommends](https://www.sge-ssn.ch/media/Nutritional-status-in-supporting-a-well-functioning-immune-system-for-optimal-health-with-a-recommendation-for-Switzerland-1.pdf) that people supplement with 2,000 IU of vitamin D per day. 
- New Zealand [provides](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/859AD0FC45E96D4300180B5C571959CD/S1368980016001683a.pdf/vitamin_d_status_and_its_predictors_in_new_zealand_agedcare_residents_eligible_for_a_governmentfunded_universal_vitamin_d_supplementation_programme.pdf) 50,000 IU monthly vitamin D supplementation to all aged care residents.
- The Scottish government [will provide](https://www.thetimes.co.uk/article/coronavirus-in-scotland-vulnerable-will-receive-vitamin-d-supplements-zc8stdpkh) vulnerable populations with vitamin D supplementats. 

*Does not support supplementation*

- NICE, an English clinical research group, [does not recommend](https://www.nice.org.uk/advice/es28/chapter/Key-messages) vitamin D supplementation. (Nice.org.u, June 29 2020)

# Lit reviews and clinical guidance

*If you only have time for one review*

- [A Basic Review of the Preliminary Evidence That COVID-19 Risk and Severity Is Increased in Vitamin D Deficiency](https://www.frontiersin.org/articles/10.3389/fpubh.2020.00513/full) note that this review only included studies which were available prior to July 2020, so did not include the COVIDIOL pilot RCT. (Benskin, Sept 2020) 

*Other reviews*

- [This review](https://www.preprints.org/manuscript/202005.0265/v1)  of potential vitamin D mechanisms of action provides some useful history on the origin of vitamin D dosing recommendations. They also review their clinical guidelines after treating several thousand patients with 5000-10000 IU/day, including recognizing and resolving  hypercalcemia or other adverse events. (McCullough, May 15 2020)
- A [review in Nature](https://www.nature.com/articles/s41430-020-0661-0) suggests that all patients should be monitored and potentially treated for vitamin D deficiency. (Ebadi et al, May 2020)
- A [bmj report](https://nutrition.bmj.com/content/3/1/106) which is generally critical of the connection between Covid-19 and vitamin D nevertheless concludes that supplementation according to government health guidelines (no more than 4,000 IU/day) is sensible for most people. (Lanham-new, May 2020) 
- A quarantine hospital in Egypt has [started providing](https://www.egypttoday.com/Article/1/88198/Doctors-in-Egypt%E2%80%99s-quarantine-hospitals-to-receive-million-Vitamin-D) (Egypt Today, News source, June 1st 2020) vitamin D to fronting medical workers. 
- A [review of the evidence](https://nutrition.bmj.com/content/bmjnph/early/2020/05/13/bmjnph-2020-000089.full.pdf) finds that supplementing with vitamin D in accordance with government guidelines is a good idea, but there is no evidence to support supplementation rates higher than 4,000 IU/day. (Lanham-New et al, April 2020)
- a [Commentary](https://www.metabolismjournal.com/article/S0026-0495(20)30186-4/) in Metabolism Journal calling for action to eliminate Vitamin D deficiencies, and recommending a higher Vitamin D advice during the pandemic of 1000-2000 IU a day. (Manson et al, July 23, 2020) 
